// Wendler 5/3/1 Forever template knowledge base. Source-of-truth metadata
// for the named templates in the book, used by the Periodizer agent +
// chat orchestrator to recommend template switches grounded in Wendler's
// own writing. Each entry cites the book page so recommendations can
// reference the source.

import type { MainScheme } from './waves';
import type { SupplementalTemplateId } from './supplemental';
import type { BlockKind } from './blocks';

export type CnsLoad = 'low' | 'moderate' | 'high' | 'very-high';
export type ConditioningCompatibility = 'incompatible' | 'low' | 'medium' | 'high';
export type HypertrophyTier = 'low' | 'moderate' | 'high' | 'very-high';
export type StrengthTier = 'low' | 'moderate' | 'high' | 'very-high';
export type Audience = 'beginner' | 'intermediate' | 'advanced' | 'all-levels';

export interface WendlerTemplate {
  id: string;
  name: string;
  bookPage: string;
  summary: string;
  blockKind: BlockKind;
  mainScheme: MainScheme;
  mainSchemeNote?: string;
  supplementalTemplate: SupplementalTemplateId | 'unsupported';
  supplementalNote?: string;
  amrap: 'always' | 'anchor-only' | 'never' | 'pr-set-only';
  cnsLoad: CnsLoad;
  strengthTier: StrengthTier;
  hypertrophyTier: HypertrophyTier;
  conditioningCompatibility: ConditioningCompatibility;
  daysPerWeek: number[];
  /** Tuple of [easyDays, hardDays] of conditioning the template tolerates. */
  conditioningDaysEasy: [number, number];
  conditioningDaysHard: [number, number];
  recommendedDurationBlocks: { min: number; max: number };
  audience: Audience;
  goalEmphasis: string[];
  cautions: string[];
  /** Successor template ids when the book recommends a Leader→Anchor pairing. */
  pairsWith?: string[];
}

/**
 * Relative ordering of CNS-load tiers. Used by sortByCnsLoad and by the
 * Periodizer when reasoning about "step down" vs "step up" recommendations.
 */
export const CNS_LOAD_RANK: Record<CnsLoad, number> = {
  low: 0,
  moderate: 1,
  high: 2,
  'very-high': 3,
};

export const WENDLER_TEMPLATES: WendlerTemplate[] = [
  // ─────────────────────────── LEADERS ───────────────────────────
  {
    id: 'bbb-leader',
    name: 'Boring But Big (Leader)',
    bookPage: 'p.45–51',
    summary:
      "5's PRO main work + 5×10 BBB at 50/60/70% TM. Wendler's classic mass-builder; used as a Leader for 2 cycles.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'bbb',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [0, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['size', 'work-capacity'],
    cautions: [
      'Volume is high — keep assistance light.',
      'Not for lifters pushing hard conditioning at the same time.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl', '531-widowmaker', 'fsl-amrap-anchor'],
  },
  {
    id: 'bbb-forever',
    name: 'BBB Forever (3/5/1)',
    bookPage: 'p.45–58',
    summary:
      "Same as BBB Leader but run with 3/5/1 main-set ordering so the heavier 3s wave comes first. 5's PRO + 5×10 @ 50/60/70%.",
    blockKind: 'leader',
    mainScheme: '351',
    mainSchemeNote:
      "Book recommends 3/5/1 for almost every Leader; BBB Forever is the 3/5/1 flavour with 5's PRO main work.",
    supplementalTemplate: 'bbb',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [0, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['size', 'work-capacity'],
    cautions: [
      'Volume is high — keep assistance light.',
      'Not for lifters pushing hard conditioning at the same time.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl', '531-widowmaker'],
  },
  {
    id: 'bbb-challenge',
    name: 'BBB Challenge (3-month)',
    bookPage: 'p.49–50',
    summary:
      "3-cycle BBB challenge: 5's PRO + 5×10 ramping 50→60→70% TM each cycle. Done with a single supplemental lift mirroring the main lift.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'bbb',
    supplementalNote:
      'Supplemental lift = same lift as the main work for the entire 3 cycles. Book stresses using the correct (conservative) TM.',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'moderate',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'incompatible',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 0],
    recommendedDurationBlocks: { min: 3, max: 3 },
    audience: 'advanced',
    goalEmphasis: ['size', 'mass-gain'],
    cautions: [
      'Do not attempt if new to BBB.',
      'Do not over-estimate the training max in hope of "adding mass".',
      'Hard conditioning is incompatible — eat and sleep aggressively instead.',
    ],
  },
  {
    id: '5spro-fsl',
    name: "5's PRO + 5×5 FSL",
    bookPage: 'p.59–63',
    summary:
      "5's PRO main work + 5×5 FSL at the first working %. The book's default sustainable Leader; ideal for athletes and conditioning blocks.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 5],
    conditioningDaysHard: [2, 4],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'all-levels',
    goalEmphasis: ['sustainability', 'bar-speed', 'athlete-friendly'],
    cautions: [
      'When pushing hard conditioning, drop supplemental from 5×5 to 3×5 FSL.',
      'Cut assistance reps if conditioning load is high.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl', 'beyond-fsl', 'original-531', '531-widowmaker'],
  },
  {
    id: '5spro-ssl',
    name: "5's PRO + 5×5 SSL",
    bookPage: 'p.129–130',
    summary:
      "5's PRO main work + 5×5 SSL at the second working % (W1 75, W2 80, W3 85%). Heavier-than-FSL volume builder for advanced lifters.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'ssl',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['size', 'strength'],
    cautions: [
      'Advanced lifters only — heavier than FSL.',
      'Not compatible with hard conditioning programmes.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl'],
  },
  {
    id: 'spinal-tap-5spro',
    name: "Spinal Tap (5's PRO)",
    bookPage: 'p.119–122',
    summary:
      "5's PRO main work + a Spinal-Tap ramp (W1 65/75/85, W2 70/80/90, W3 75/85/95 × 3 reps) doubling the top sets as supplemental.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'spinal-tap',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'intensity-tolerance'],
    cautions: [
      'Top supplemental sets hit 95% TM — only run with a conservative TM.',
      'Skip on the press if recovery is poor.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl', '531-widowmaker'],
  },
  {
    id: 'spinal-tap-hs',
    name: 'Spinal Tap (High School)',
    bookPage: 'p.123–124',
    summary:
      "Wendler's original High-School Spinal Tap — same 3-set ramp at the main 5/3/1 percentages × 3 reps. Lower-volume, higher-intensity supplemental.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'spinal-tap',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'simplicity'],
    cautions: ['Top supplemental hits 95% TM — keep TM honest.'],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl'],
  },
  {
    id: 'coffinworm',
    name: 'Coffinworm',
    bookPage: 'p.125–128',
    summary:
      "Heavy minimalist Leader — Week 1 & 2 identical (Spinal-Tap-style ramp + 5×5 FSL); Week 3 is a semi-deload. Run for 2 cycles.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    mainSchemeNote:
      "Main work mirrors Spinal-Tap percentages with a built-in semi-deload on Week 3; closest scheme in the codebase is 5's PRO.",
    supplementalTemplate: 'unsupported',
    supplementalNote:
      'Combination of a Spinal-Tap-style top-set ramp and 5×5 FSL — not a single SupplementalTemplateId.',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'very-high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['strength', 'heavy-handling'],
    cautions: [
      'Ideal for intermediate-to-advanced lifters at 85–90% TM.',
      'Week 1 & 2 are identical heavy weeks — Week 3 is a semi-deload, do not skip it.',
    ],
  },
  {
    id: 'god-is-a-beast-leader',
    name: 'God Is A Beast (Leader)',
    bookPage: 'p.107–110',
    summary:
      "2-cycle high-volume Leader for size + strength. Combines Boring But Strong-style supplemental with Spinal-Tap pieces. 85% TM.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'unsupported',
    supplementalNote:
      'Book describes a hybrid of Boring But Strong and Spinal Tap variations — no single SupplementalTemplateId captures it.',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['size', 'strength'],
    cautions: [
      'Horrible for impatient lifters.',
      'Requires a lot of training time and excellent recovery.',
      '2 cycles only, then transition to the Anchor.',
    ],
    pairsWith: ['fsl-amrap-anchor', 'pr-set-fsl'],
  },
  {
    id: 'pervertor',
    name: 'Pervertor',
    bookPage: 'p.161–162',
    summary:
      "3/5/1 Leader with Widowmaker supplemental on Week 1 and progressively heavier high-rep work. 2–3 cycles before the Pervertor Anchor.",
    blockKind: 'leader',
    mainScheme: '351',
    supplementalTemplate: 'widowmaker',
    supplementalNote:
      'Widowmaker (1×20 @ FSL) on the first week, then drops to lower-rep supplemental on later weeks.',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 2, max: 3 },
    audience: 'advanced',
    goalEmphasis: ['size', 'mental-toughness'],
    cautions: [
      'Widowmaker squats and deadlifts are brutal — keep TM conservative.',
      'Easy conditioning only.',
    ],
    pairsWith: ['pervertor-anchor', '531-widowmaker'],
  },
  {
    id: 'krypteia-p1',
    name: 'Krypteia, Part One',
    bookPage: 'p.233–235',
    summary:
      "Preparatory phase (2 cycles). 5's Progression + 5×5 FSL on the main lifts. Lays the aerobic / volume base for parts 2 and 3.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 3],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['conditioning', 'base-building', 'fat-loss'],
    cautions: [
      "Don't skip — Part Two relies on the aerobic base built here.",
      "Use 5's PRO; book explicitly says not to choose a heavier scheme.",
    ],
    pairsWith: ['krypteia-p2'],
  },
  {
    id: 'krypteia-p2',
    name: 'Krypteia, Part Two',
    bookPage: 'p.235–237',
    summary:
      "Middle phase of Krypteia. Higher-volume main work with continued conditioning emphasis and assistance pulled into a circuit style.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote:
      'Supplemental remains FSL but assistance is circuit-style alongside heavy conditioning. Not a custom supplemental template.',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 4],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['conditioning', 'fat-loss', 'work-capacity'],
    cautions: [
      'Only run after Part One — do not jump in cold.',
      'Recovery / sleep / nutrition need to be locked in.',
    ],
    pairsWith: ['krypteia-p3'],
  },
  {
    id: 'black-army-jacket',
    name: 'Black Army Jacket (Leader)',
    bookPage: 'p.115–116',
    summary:
      "Mirrored 4-day Leader using Spinal-Tap-style work for the heavy lifts and 5's PRO for the others. Strength + size with built-in symmetry.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'spinal-tap',
    supplementalNote:
      "Spinal-Tap supplemental on the lifts you're pushing; the other two lifts run 5's PRO without the Spinal-Tap ramp.",
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'medium',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'balanced-development'],
    cautions: ["Don't push Spinal Tap on every lift — pick two."],
    pairsWith: ['black-army-jacket-anchor', 'pr-joker-fsl'],
  },
  {
    id: 'simplest-strength',
    name: 'Simplest Strength Template (SST)',
    bookPage: 'p.105–106',
    summary:
      "5's PRO + SST supplemental — original 3-week ramp (W1 50/60/70×10, W2 60/70/80×8/6, W3 65/75/85×5). Works as Leader or Anchor.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'unsupported',
    supplementalNote:
      'SST uses 3 different percentages per week with different rep targets (10/10/10 → 10/8/6 → 5/5/5) — no equivalent SupplementalTemplateId.',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 5],
    conditioningDaysHard: [1, 3],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'all-levels',
    goalEmphasis: ['variety', 'sustainability'],
    cautions: ['Use 85–90% TM as the book recommends for all variations.'],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl', '531-widowmaker', 'fsl-amrap-anchor'],
  },
  {
    id: 'morning-star',
    name: 'The Morning Star',
    bookPage: 'p.81–82',
    summary:
      "2–3 cycle Leader using 5's PRO with a Spinal-Tap-style variation on the supplemental. Volume/strength bias before the Morning Star Anchor.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'spinal-tap',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'medium',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 3 },
    audience: 'intermediate',
    goalEmphasis: ['size', 'strength'],
    cautions: ['Run 2–3 cycles before switching to the Anchor variant.'],
    pairsWith: ['morning-star-anchor', 'pr-set-fsl'],
  },
  {
    id: 'volume-strength',
    name: 'Volume And Strength (Leader)',
    bookPage: 'p.85–86',
    summary:
      "Leader template emphasising volume work behind 5's PRO main sets. Pairs into Volume And Strength Anchor or a PR-set Anchor.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'bbb',
    supplementalNote:
      'Book describes high-volume supplemental — closest codebase model is BBB; book also mentions "Boring But Strong" as an alternative variant.',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['size', 'strength'],
    cautions: ['Volume is high — hard conditioning is not compatible.'],
    pairsWith: ['pr-set-fsl', '531-widowmaker'],
  },
  {
    id: 'five-x-531',
    name: '5×5/3/1 (Leader)',
    bookPage: 'p.87–92',
    summary:
      "5's PRO with 5×5 of a supplemental lift at FSL percentages. Sustainable, athlete-friendly Leader. Anchor partner on p.93–96.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 3],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'all-levels',
    goalEmphasis: ['sustainability', 'bar-speed'],
    cautions: ['Keep bar speed honest on FSL sets — back off when it slows for >2 weeks.'],
    pairsWith: ['five-x-531-anchor', 'pr-set-fsl', 'fsl-amrap-anchor'],
  },
  {
    id: 'full-body-1000pct',
    name: 'Full Body, 1000% Awesome',
    bookPage: 'p.73–76',
    summary:
      "Full-body 3-day Leader with a lot of supplemental work. 5's PRO main + FSL-style volume. For lifters who recover well from full-body sessions.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'very-high',
    conditioningCompatibility: 'low',
    daysPerWeek: [3],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [0, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['size', 'work-capacity'],
    cautions: [
      'Supplemental volume is heavy — only for lifters who recover well from full-body sessions.',
    ],
    pairsWith: ['pr-set-fsl', '531-widowmaker'],
  },
  {
    id: 'svr-ii',
    name: 'S.V.R. II',
    bookPage: 'p.77–80',
    summary:
      "Strength / Volume / Recovery rotation across the 3 weeks. 5's PRO with rotating supplemental load — not required on every lift.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'unsupported',
    supplementalNote:
      'SVR II rotates between a Strength week, a Volume week and a Recovery week with different load + rep schemes — no single SupplementalTemplateId.',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'recovery-rotation'],
    cautions: ['You can opt out of SVR II per-lift — use 5×5 FSL instead on any lift you skip.'],
    pairsWith: ['svr-ii-anchor', 'pr-set-fsl'],
  },
  {
    id: 'full-body-squat-push-pull',
    name: 'Full Body — Squat, Push, Pull',
    bookPage: 'p.145–154',
    summary:
      "Multi-variant full-body Leader catalogue (Full Body 1–13). Each variant pairs a main lift with a push and pull supplemental of varying volume.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote:
      'Catalogue of 13 full-body variants — most default to FSL on the main lift with extra push/pull volume. Some variants use Widowmaker on the Friday squat.',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['size', 'balanced-development'],
    cautions: [
      'Schedule the Widowmaker (when used) on Friday so recovery days follow.',
      'Multiple variants — pick one and stick with it for the block.',
    ],
    pairsWith: ['pr-set-fsl', 'pr-joker-fsl'],
  },
  {
    id: 'five-and-dime',
    name: 'Five And Dime (Leader)',
    bookPage: 'p.101–102',
    summary:
      "3-day/week A/B-rotation Leader. 5's PRO main work + FSL-style supplemental aimed at finishing each session in ~40–45 minutes.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [1, 3],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'all-levels',
    goalEmphasis: ['time-efficient', 'sustainability'],
    cautions: ['Each session is meant to be brisk — pad rests, not exercise count.'],
    pairsWith: ['five-and-dime-anchor', 'pr-set-fsl'],
  },
  {
    id: 'leviathan-leader',
    name: 'Leviathan (Leader)',
    bookPage: 'p.199–200',
    summary:
      "Heavy minimalist Leader — work up to a single top set on each main lift, then FSL-style supplemental. Pairs with the Leviathan Anchor.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'very-high',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'medium',
    daysPerWeek: [4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['strength', 'heavy-handling'],
    cautions: ['Top single demands an honest TM; not for novices.'],
    pairsWith: ['leviathan-anchor', 'pr-set-fsl'],
  },
  {
    id: 'strength-circuits-leader',
    name: '5/3/1 Strength Circuits (Leader)',
    bookPage: 'p.211–214',
    summary:
      "Circuit-style Leader interleaving main 5's PRO sets with assistance pairings to compress the session and add conditioning.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote:
      'Supplemental FSL is woven into assistance circuits — preserves load but changes the session structure.',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 3],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['conditioning', 'time-efficient'],
    cautions: ['Heart rate stays elevated — do not also push hard conditioning days.'],
    pairsWith: ['strength-circuits-anchor', 'pr-set-fsl'],
  },
  {
    id: 'widowmaker-circuit',
    name: 'Widowmaker Circuit (Leader)',
    bookPage: 'p.225–228',
    summary:
      "Leader pairing a Widowmaker squat/deadlift set with a press/bench supplemental in a brief circuit. Conditioning-flavoured strength work.",
    blockKind: 'leader',
    mainScheme: '5s-pro',
    supplementalTemplate: 'widowmaker',
    amrap: 'never',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 2, max: 2 },
    audience: 'advanced',
    goalEmphasis: ['conditioning', 'mental-toughness'],
    cautions: [
      '20-rep squats/deadlifts are brutal — keep TM conservative.',
      'Anchor variant removes the Widowmaker — do not stack both phases.',
    ],
    pairsWith: ['widowmaker-circuit-anchor', 'pr-set-fsl'],
  },

  // ─────────────────────────── ANCHORS ───────────────────────────
  {
    id: 'pr-set-fsl',
    name: 'PR Set + 5×5 FSL (Anchor)',
    bookPage: 'p.64–66',
    summary:
      "Classic 5/3/1 main sets with an AMRAP PR set on the top set, plus 5×5 FSL. The book's default Anchor.",
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    supplementalTemplate: 'fsl',
    amrap: 'anchor-only',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'all-levels',
    goalEmphasis: ['strength', 'pr-push'],
    cautions: ['Save the all-out PR set for Week 3 — pace yourself in Weeks 1–2.'],
  },
  {
    id: 'pr-joker-fsl',
    name: 'PR Set + Jokers + 5×5 FSL (Anchor)',
    bookPage: 'p.66–68',
    summary:
      'Classic 5/3/1 with PR set + Joker singles/doubles above the top % + 5×5 FSL. Maximum-intensity Anchor for advanced lifters.',
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    supplementalTemplate: 'fsl',
    supplementalNote:
      "Jokers are layered on top of the main work and not modelled separately — they sit between 'main' and 'supplemental' in the codebase.",
    amrap: 'anchor-only',
    cnsLoad: 'very-high',
    strengthTier: 'very-high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'advanced',
    goalEmphasis: ['strength', 'pr-push'],
    cautions: [
      'Jokers are Wendler\'s "biggest regret" if abused — stop when bar speed drops.',
      'Do not chase Jokers on every lift every week.',
    ],
  },
  {
    id: '531-widowmaker',
    name: '5/3/1 + Widowmaker (Anchor)',
    bookPage: 'p.68–69',
    summary:
      "Classic 5/3/1 PR sets followed by a single Widowmaker set (1×20 @ first working %). Squat / deadlift Anchor with a conditioning sting.",
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    supplementalTemplate: 'widowmaker',
    amrap: 'anchor-only',
    cnsLoad: 'very-high',
    strengthTier: 'high',
    hypertrophyTier: 'high',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'mental-toughness'],
    cautions: [
      '20-rep squats / deadlifts — schedule on the final session of the week.',
      'Not for lifters with current low-back / hip flags.',
    ],
  },
  {
    id: 'fsl-amrap-anchor',
    name: 'FSL AMRAP (Anchor)',
    bookPage: 'p.59–63',
    summary:
      "Classic 5/3/1 main sets with a single AMRAP set at FSL. Gauges progress without big volume — light Anchor option.",
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    supplementalTemplate: 'fsl-amrap',
    amrap: 'anchor-only',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 3],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'all-levels',
    goalEmphasis: ['sustainability', 'tracking-progress'],
    cautions: ['One AMRAP per session — push it, do not stretch it across multiple sets.'],
  },
  {
    id: 'beyond-fsl',
    name: 'Beyond + FSL (Anchor)',
    bookPage: 'p.70–73',
    summary:
      "Beyond 5/3/1 main work (heavier than the standard 5/3/1 percentages) + 5×5 FSL. Advanced Anchor for experienced lifters only.",
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    mainSchemeNote:
      "Book's Beyond programming uses heavier-than-standard main-set percentages; codebase only models classic-531 so users get the standard AMRAP wave.",
    supplementalTemplate: 'fsl',
    amrap: 'anchor-only',
    cnsLoad: 'very-high',
    strengthTier: 'very-high',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'low',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [2, 3],
    conditioningDaysHard: [0, 1],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'advanced',
    goalEmphasis: ['strength', 'pr-push'],
    cautions: [
      'For advanced lifters with significant self-coaching experience only.',
      'Not for beginners or anyone short on training experience.',
    ],
  },
  {
    id: 'krypteia-p3',
    name: 'Krypteia, Part Three (Anchor)',
    bookPage: 'p.239–241',
    summary:
      "Anchor phase of Krypteia. 3×3 heavy main work + reduced volume — caps off the conditioning-led block with a strength push.",
    blockKind: 'anchor',
    mainScheme: 'classic-531',
    mainSchemeNote: 'Book uses a 3×3 heavy structure as the Anchor; the closest match is classic 5/3/1.',
    supplementalTemplate: 'fsl-amrap',
    supplementalNote:
      'Book reduces supplemental reps to threes; FSL-AMRAP is the closest available codebase model.',
    amrap: 'anchor-only',
    cnsLoad: 'high',
    strengthTier: 'high',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 1, max: 1 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'conditioning-finish'],
    cautions: [
      'Run only after Krypteia Parts 1 and 2.',
      'Can re-run Krypteia by skipping Part 1 on repeat cycles per book guidance.',
    ],
  },

  // ─────────────────────────── STANDALONES ───────────────────────────
  {
    id: 'beginner-prep',
    name: 'Beginner Prep School',
    bookPage: 'p.39–43',
    summary:
      "Wendler's onboarding programme. Conservative TM, 5's PRO main work, light supplemental and high-frequency practice for new lifters.",
    blockKind: 'standalone',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'low',
    strengthTier: 'low',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [0, 2],
    recommendedDurationBlocks: { min: 3, max: 6 },
    audience: 'beginner',
    goalEmphasis: ['technique', 'consistency'],
    cautions: [
      'Use 90% TM on solid lifts and 85% on the struggling ones — do not chase weight.',
      'Drop the AMRAP set entirely while learning technique.',
    ],
  },
  {
    id: 'original-531',
    name: 'Original 5/3/1',
    bookPage: 'p.168–169',
    summary:
      'The original Wendler 5/3/1 programme — classic 5/3/1 waves with AMRAP top sets, no supplemental volume. The benchmark template.',
    blockKind: 'standalone',
    mainScheme: 'classic-531',
    supplementalTemplate: 'none',
    amrap: 'always',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [2, 3],
    recommendedDurationBlocks: { min: 1, max: 4 },
    audience: 'all-levels',
    goalEmphasis: ['strength', 'sustainability'],
    cautions: ['Without supplemental work, hypertrophy progress is slow — pair with assistance.'],
  },
  {
    id: 'original-531-fsl',
    name: 'Original 5/3/1 + FSL',
    bookPage: 'p.169–170',
    summary:
      'Original 5/3/1 with PR sets plus 5×5 FSL as Anchor-style standalone. The most common entry point to template-based programming.',
    blockKind: 'standalone',
    mainScheme: 'classic-531',
    supplementalTemplate: 'fsl',
    amrap: 'always',
    cnsLoad: 'moderate',
    strengthTier: 'moderate',
    hypertrophyTier: 'moderate',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [1, 3],
    recommendedDurationBlocks: { min: 1, max: 4 },
    audience: 'all-levels',
    goalEmphasis: ['strength', 'sustainability'],
    cautions: ['Keep bar speed honest on FSL — drop a set if it crawls.'],
  },
  {
    id: '2x2x2',
    name: '2x2x2',
    bookPage: 'p.231–232',
    summary:
      "Three training categories split across 2 days each: conditioning, mobility, and lifting. Maintenance / general-prep standalone.",
    blockKind: 'standalone',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote:
      'Programme is built around equal time blocks for conditioning, mobility and lifting — supplemental work is kept minimal so the FSL model captures it loosely.',
    amrap: 'never',
    cnsLoad: 'low',
    strengthTier: 'low',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [2],
    conditioningDaysEasy: [2, 4],
    conditioningDaysHard: [1, 2],
    recommendedDurationBlocks: { min: 1, max: 4 },
    audience: 'all-levels',
    goalEmphasis: ['general-prep', 'maintenance'],
    cautions: ['Lifting is the smallest part of the week — not for PR pushes.'],
  },
  {
    id: 'conclavi-condio',
    name: 'Conclavi Condio',
    bookPage: 'p.201–203',
    summary:
      "Conditioning-led standalone built around flexibility + mobility work alongside light 5's PRO lifting. For periods of high cardio load.",
    blockKind: 'standalone',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote: 'Drop to 3×5 FSL when conditioning load is heavy, per book guidance.',
    amrap: 'never',
    cnsLoad: 'low',
    strengthTier: 'low',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 6],
    conditioningDaysHard: [2, 4],
    recommendedDurationBlocks: { min: 1, max: 3 },
    audience: 'all-levels',
    goalEmphasis: ['conditioning', 'mobility'],
    cautions: [
      'Use during high conditioning load — strength gains will be modest.',
      'Pair with a strength-led Leader on either side.',
    ],
  },
  {
    id: 'prowler-challenge',
    name: '5/3/1 Prowler Challenge',
    bookPage: 'p.171–174',
    summary:
      "Standalone challenge pairing 5/3/1 lifting with daily Prowler / sled conditioning. Strength + conditioning push for those with the equipment.",
    blockKind: 'standalone',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    amrap: 'never',
    cnsLoad: 'high',
    strengthTier: 'moderate',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 6],
    conditioningDaysHard: [3, 5],
    recommendedDurationBlocks: { min: 1, max: 2 },
    audience: 'intermediate',
    goalEmphasis: ['conditioning', 'fat-loss'],
    cautions: [
      'Requires a Prowler / sled and a surface that tolerates one.',
      'Do not stack with another heavy conditioning challenge.',
    ],
  },
  {
    id: 'original-531-challenge',
    name: 'Original 5/3/1 Challenge',
    bookPage: 'p.175–180',
    summary:
      "Multi-cycle challenge built on Original 5/3/1 with explicit PR targets. Standalone benchmark to test all four lifts over a fixed run.",
    blockKind: 'standalone',
    mainScheme: 'classic-531',
    supplementalTemplate: 'none',
    amrap: 'always',
    cnsLoad: 'moderate',
    strengthTier: 'high',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'medium',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [3, 5],
    conditioningDaysHard: [1, 3],
    recommendedDurationBlocks: { min: 3, max: 3 },
    audience: 'intermediate',
    goalEmphasis: ['strength', 'pr-push'],
    cautions: [
      'Use a conservative TM — challenge demands honest rep counts each cycle.',
    ],
  },
  {
    id: 'prep-fat-loss',
    name: 'Prep And Fat Loss Training',
    bookPage: 'p.205–209',
    summary:
      "Conditioning-heavy standalone for fat-loss / general athletic prep. Light 5's PRO main work + 3×5 FSL with daily conditioning.",
    blockKind: 'standalone',
    mainScheme: '5s-pro',
    supplementalTemplate: 'fsl',
    supplementalNote: 'Drop FSL to 3×5 to leave room for the conditioning load.',
    amrap: 'never',
    cnsLoad: 'moderate',
    strengthTier: 'low',
    hypertrophyTier: 'low',
    conditioningCompatibility: 'high',
    daysPerWeek: [3, 4],
    conditioningDaysEasy: [4, 6],
    conditioningDaysHard: [2, 4],
    recommendedDurationBlocks: { min: 1, max: 3 },
    audience: 'all-levels',
    goalEmphasis: ['fat-loss', 'conditioning'],
    cautions: [
      'Strength gains will be small — that is the point.',
      'Build an aerobic base first; not for runners >30 km/week without prior base.',
    ],
  },
];

// ─────────────────────────── Helpers ───────────────────────────

export const LEADER_TEMPLATES = WENDLER_TEMPLATES.filter((t) => t.blockKind === 'leader');
export const ANCHOR_TEMPLATES = WENDLER_TEMPLATES.filter((t) => t.blockKind === 'anchor');
export const STANDALONE_TEMPLATES = WENDLER_TEMPLATES.filter((t) => t.blockKind === 'standalone');

export const SUPPORTED_TEMPLATES = WENDLER_TEMPLATES.filter(
  (t) => t.supplementalTemplate !== 'unsupported',
);
export const UNSUPPORTED_TEMPLATES = WENDLER_TEMPLATES.filter(
  (t) => t.supplementalTemplate === 'unsupported',
);

export function getTemplateById(id: string): WendlerTemplate | undefined {
  return WENDLER_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByScheme(scheme: MainScheme): WendlerTemplate[] {
  return WENDLER_TEMPLATES.filter((t) => t.mainScheme === scheme);
}

export function getTemplatesBySupplemental(
  supp: SupplementalTemplateId | 'unsupported',
): WendlerTemplate[] {
  return WENDLER_TEMPLATES.filter((t) => t.supplementalTemplate === supp);
}

export function getTemplatesByConditioningLoad(
  compat: ConditioningCompatibility,
): WendlerTemplate[] {
  return WENDLER_TEMPLATES.filter((t) => t.conditioningCompatibility === compat);
}

export function sortByCnsLoad(
  templates: WendlerTemplate[] = WENDLER_TEMPLATES,
  direction: 'asc' | 'desc' = 'asc',
): WendlerTemplate[] {
  const factor = direction === 'asc' ? 1 : -1;
  return [...templates].sort(
    (a, b) => factor * (CNS_LOAD_RANK[a.cnsLoad] - CNS_LOAD_RANK[b.cnsLoad]),
  );
}

/**
 * Book-recommended Leader → Anchor pairings. The Periodizer agent uses this
 * to suggest a successor block when finishing a Leader, citing the source
 * page from the matching `WendlerTemplate.bookPage`.
 */
export const RECOMMENDED_PAIRINGS: { leader: string; anchor: string }[] = [
  { leader: 'bbb-leader', anchor: 'pr-set-fsl' },
  { leader: 'bbb-leader', anchor: 'pr-joker-fsl' },
  { leader: 'bbb-leader', anchor: '531-widowmaker' },
  { leader: 'bbb-forever', anchor: 'pr-set-fsl' },
  { leader: 'bbb-forever', anchor: '531-widowmaker' },
  { leader: '5spro-fsl', anchor: 'pr-set-fsl' },
  { leader: '5spro-fsl', anchor: 'pr-joker-fsl' },
  { leader: '5spro-fsl', anchor: 'beyond-fsl' },
  { leader: '5spro-fsl', anchor: '531-widowmaker' },
  { leader: '5spro-ssl', anchor: 'pr-set-fsl' },
  { leader: '5spro-ssl', anchor: 'pr-joker-fsl' },
  { leader: 'spinal-tap-5spro', anchor: 'pr-set-fsl' },
  { leader: 'spinal-tap-5spro', anchor: 'pr-joker-fsl' },
  { leader: 'spinal-tap-hs', anchor: 'pr-set-fsl' },
  { leader: 'simplest-strength', anchor: 'pr-set-fsl' },
  { leader: 'simplest-strength', anchor: '531-widowmaker' },
  { leader: 'simplest-strength', anchor: 'beyond-fsl' },
  { leader: 'simplest-strength', anchor: 'fsl-amrap-anchor' },
  { leader: 'god-is-a-beast-leader', anchor: 'fsl-amrap-anchor' },
  { leader: 'god-is-a-beast-leader', anchor: 'pr-set-fsl' },
  { leader: 'pervertor', anchor: '531-widowmaker' },
  { leader: 'krypteia-p1', anchor: 'krypteia-p3' },
  { leader: 'krypteia-p2', anchor: 'krypteia-p3' },
  { leader: 'five-x-531', anchor: 'pr-set-fsl' },
  { leader: 'five-x-531', anchor: 'fsl-amrap-anchor' },
  { leader: 'full-body-1000pct', anchor: 'pr-set-fsl' },
  { leader: 'full-body-1000pct', anchor: '531-widowmaker' },
  { leader: 'volume-strength', anchor: 'pr-set-fsl' },
  { leader: 'morning-star', anchor: 'pr-set-fsl' },
  { leader: 'black-army-jacket', anchor: 'pr-joker-fsl' },
  { leader: 'five-and-dime', anchor: 'pr-set-fsl' },
  { leader: 'leviathan-leader', anchor: 'pr-set-fsl' },
  { leader: 'strength-circuits-leader', anchor: 'pr-set-fsl' },
  { leader: 'widowmaker-circuit', anchor: 'pr-set-fsl' },
  { leader: 'full-body-squat-push-pull', anchor: 'pr-set-fsl' },
  { leader: 'full-body-squat-push-pull', anchor: 'pr-joker-fsl' },
  { leader: 'svr-ii', anchor: 'pr-set-fsl' },
];
