import type { Movement } from './types';

/**
 * Built-in movement library. Stable IDs use the prefix `seed:` so they never collide with
 * user-created movements.
 */
export const SEED_MOVEMENTS: Movement[] = [
  // The Big Four (5/3/1 main lifts)
  {
    id: 'seed:back-squat',
    name: 'Back Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'erectors'],
    isMainLift: 'squat',
    isCompound: true,
  },
  {
    id: 'seed:bench-press',
    name: 'Bench Press',
    equipment: 'barbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    isMainLift: 'bench',
    isCompound: true,
  },
  {
    id: 'seed:deadlift',
    name: 'Deadlift',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes', 'erectors'],
    secondaryMuscles: ['back', 'lats', 'traps', 'forearms'],
    isMainLift: 'deadlift',
    isCompound: true,
  },
  {
    id: 'seed:overhead-press',
    name: 'Overhead Press',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    isMainLift: 'press',
    isCompound: true,
  },

  // Common supplemental / assistance
  {
    id: 'seed:front-squat',
    name: 'Front Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['core', 'glutes', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:safety-bar-squat',
    name: 'Safety Bar Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'erectors', 'traps'],
    isCompound: true,
  },
  {
    id: 'seed:trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    equipment: 'trap-bar',
    pattern: 'hinge',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    secondaryMuscles: ['back', 'traps', 'forearms', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:sumo-deadlift',
    name: 'Sumo Deadlift',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'quads'],
    secondaryMuscles: ['back', 'traps', 'forearms', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:push-press',
    name: 'Push Press',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'quads', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:romanian-deadlift',
    name: 'Romanian Deadlift',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors', 'forearms'],
    isCompound: true,
  },
  {
    id: 'seed:incline-bench',
    name: 'Incline Bench Press',
    equipment: 'barbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps'],
    isCompound: true,
  },
  {
    id: 'seed:close-grip-bench',
    name: 'Close-Grip Bench Press',
    equipment: 'barbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    isCompound: true,
  },

  // Pulling
  {
    id: 'seed:pullup',
    name: 'Pull-up',
    equipment: 'bodyweight',
    pattern: 'pull-vertical',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'forearms'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:chinup',
    name: 'Chin-up',
    equipment: 'bodyweight',
    pattern: 'pull-vertical',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['back', 'forearms'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:barbell-row',
    name: 'Barbell Row',
    equipment: 'barbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'erectors'],
  },
  {
    id: 'seed:db-row',
    name: 'Dumbbell Row',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms'],
  },

  // Accessories
  {
    id: 'seed:db-bench',
    name: 'Dumbbell Bench Press',
    equipment: 'dumbbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    isCompound: true,
  },
  {
    id: 'seed:db-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    isCompound: true,
  },
  {
    id: 'seed:lunge',
    name: 'Walking Lunge',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:dip',
    name: 'Dip',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:hanging-leg-raise',
    name: 'Hanging Leg Raise',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['obliques', 'forearms'],
  },
  {
    id: 'seed:plank',
    name: 'Plank',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['obliques', 'shoulders'],
  },
  {
    id: 'seed:farmer-carry',
    name: 'Farmer Carry',
    equipment: 'dumbbell',
    pattern: 'carry',
    primaryMuscles: ['forearms', 'traps'],
    secondaryMuscles: ['core', 'shoulders'],
  },
  {
    id: 'seed:db-curl',
    name: 'Dumbbell Curl',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
  },

  // ---- Extended library (added 2026-05) ---------------------------------
  // Lower body — hinge / glute
  {
    id: 'seed:barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:glute-bridge',
    name: 'Glute Bridge',
    equipment: 'bodyweight',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:single-leg-rdl',
    name: 'Single-Leg Romanian Deadlift',
    equipment: 'dumbbell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['core', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:good-morning',
    name: 'Good Morning',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'erectors'],
    secondaryMuscles: ['glutes', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:kb-swing',
    name: 'Kettlebell Swing',
    equipment: 'kettlebell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'forearms', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:back-extension',
    name: 'Back Extension',
    equipment: 'bodyweight',
    pattern: 'hinge',
    primaryMuscles: ['erectors', 'glutes'],
    secondaryMuscles: ['hamstrings'],
  },

  // Lower body — squat / single-leg
  {
    id: 'seed:bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:goblet-squat',
    name: 'Goblet Squat',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
    isCompound: true,
  },
  {
    id: 'seed:reverse-lunge',
    name: 'Reverse Lunge',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:step-up',
    name: 'Step-up',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:box-squat',
    name: 'Box Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'erectors'],
    isCompound: true,
  },
  {
    id: 'seed:leg-press',
    name: 'Leg Press',
    equipment: 'machine',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    isCompound: true,
  },
  {
    id: 'seed:leg-extension',
    name: 'Leg Extension',
    equipment: 'machine',
    pattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:leg-curl',
    name: 'Leg Curl',
    equipment: 'machine',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
  },
  {
    id: 'seed:calf-raise',
    name: 'Standing Calf Raise',
    equipment: 'machine',
    pattern: 'squat',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
  },

  // Upper push — horizontal
  {
    id: 'seed:pushup',
    name: 'Push-up',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:incline-db-press',
    name: 'Incline Dumbbell Press',
    equipment: 'dumbbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'shoulders'],
    secondaryMuscles: ['triceps'],
    isCompound: true,
  },
  {
    id: 'seed:cable-fly',
    name: 'Cable Fly',
    equipment: 'cable',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
  },

  // Upper push — vertical / shoulders
  {
    id: 'seed:landmine-press',
    name: 'Landmine Press',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'chest', 'core'],
    isCompound: true,
  },
  {
    id: 'seed:arnold-press',
    name: 'Arnold Press',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'chest'],
    isCompound: true,
  },
  {
    id: 'seed:lateral-raise',
    name: 'Lateral Raise',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:rear-delt-fly',
    name: 'Rear Delt Fly',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: ['traps'],
  },
  {
    id: 'seed:face-pull',
    name: 'Face Pull',
    equipment: 'band',
    pattern: 'pull-horizontal',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: ['traps', 'biceps'],
  },
  {
    id: 'seed:band-pull-apart',
    name: 'Band Pull-Apart',
    equipment: 'band',
    pattern: 'pull-horizontal',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: ['traps'],
  },

  // Pulling — horizontal / vertical
  {
    id: 'seed:inverted-row',
    name: 'Inverted Row',
    equipment: 'bodyweight',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'core', 'forearms'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:lat-pulldown',
    name: 'Lat Pulldown',
    equipment: 'cable',
    pattern: 'pull-vertical',
    primaryMuscles: ['lats', 'back'],
    secondaryMuscles: ['biceps', 'forearms'],
  },
  {
    id: 'seed:seated-cable-row',
    name: 'Seated Cable Row',
    equipment: 'cable',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms'],
  },
  {
    id: 'seed:t-bar-row',
    name: 'T-Bar Row',
    equipment: 'barbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'erectors'],
  },
  {
    id: 'seed:shrug',
    name: 'Barbell Shrug',
    equipment: 'barbell',
    pattern: 'pull-vertical',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
  },

  // Arms
  {
    id: 'seed:barbell-curl',
    name: 'Barbell Curl',
    equipment: 'barbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
  },
  {
    id: 'seed:hammer-curl',
    name: 'Hammer Curl',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:preacher-curl',
    name: 'Preacher Curl',
    equipment: 'barbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
  },
  {
    id: 'seed:tricep-pushdown',
    name: 'Tricep Pushdown',
    equipment: 'cable',
    pattern: 'push-vertical',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:skull-crusher',
    name: 'Skull Crusher',
    equipment: 'barbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
  },
  {
    id: 'seed:overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['shoulders'],
  },

  // Core
  {
    id: 'seed:ab-wheel',
    name: 'Ab Wheel Rollout',
    equipment: 'other',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lats', 'shoulders', 'obliques'],
  },
  {
    id: 'seed:pallof-press',
    name: 'Pallof Press',
    equipment: 'band',
    pattern: 'core',
    primaryMuscles: ['core', 'obliques'],
    secondaryMuscles: ['shoulders'],
  },
  {
    id: 'seed:side-plank',
    name: 'Side Plank',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: ['shoulders', 'glutes'],
  },
  {
    id: 'seed:dead-bug',
    name: 'Dead Bug',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['obliques'],
  },
  {
    id: 'seed:bird-dog',
    name: 'Bird Dog',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core', 'erectors'],
    secondaryMuscles: ['glutes', 'shoulders'],
  },
  {
    id: 'seed:russian-twist',
    name: 'Russian Twist',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:cable-crunch',
    name: 'Cable Crunch',
    equipment: 'cable',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['obliques'],
  },

  // Carries / conditioning
  {
    id: 'seed:goblet-carry',
    name: 'Goblet Carry',
    equipment: 'dumbbell',
    pattern: 'carry',
    primaryMuscles: ['core', 'forearms'],
    secondaryMuscles: ['shoulders', 'traps'],
  },
  {
    id: 'seed:suitcase-carry',
    name: 'Suitcase Carry',
    equipment: 'dumbbell',
    pattern: 'carry',
    primaryMuscles: ['obliques', 'forearms'],
    secondaryMuscles: ['core', 'traps'],
  },
  {
    id: 'seed:sled-push',
    name: 'Sled Push',
    equipment: 'other',
    pattern: 'carry',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves', 'core'],
  },

  // ---- Functional / CrossFit library (added 2026-05) --------------------
  // Olympic & barbell complex
  {
    id: 'seed:power-clean',
    name: 'Power Clean',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'traps'],
    secondaryMuscles: ['quads', 'shoulders', 'erectors', 'forearms', 'core'],
  },
  {
    id: 'seed:hang-clean',
    name: 'Hang Clean',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'traps'],
    secondaryMuscles: ['quads', 'shoulders', 'erectors', 'forearms', 'core'],
  },
  {
    id: 'seed:squat-clean',
    name: 'Squat Clean',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'quads', 'hamstrings', 'traps'],
    secondaryMuscles: ['shoulders', 'erectors', 'forearms', 'core'],
  },
  {
    id: 'seed:power-snatch',
    name: 'Power Snatch',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders', 'traps'],
    secondaryMuscles: ['quads', 'back', 'core', 'forearms'],
  },
  {
    id: 'seed:squat-snatch',
    name: 'Squat Snatch',
    equipment: 'barbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders', 'traps', 'quads'],
    secondaryMuscles: ['back', 'core', 'forearms'],
  },
  {
    id: 'seed:clean-and-jerk',
    name: 'Clean & Jerk',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['glutes', 'quads', 'shoulders', 'traps'],
    secondaryMuscles: ['hamstrings', 'triceps', 'core', 'erectors'],
  },
  {
    id: 'seed:push-jerk',
    name: 'Push Jerk',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'quads'],
    secondaryMuscles: ['triceps', 'glutes', 'core'],
  },
  {
    id: 'seed:split-jerk',
    name: 'Split Jerk',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'quads'],
    secondaryMuscles: ['triceps', 'glutes', 'core', 'hamstrings'],
  },
  {
    id: 'seed:thruster',
    name: 'Thruster',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['quads', 'glutes', 'shoulders'],
    secondaryMuscles: ['triceps', 'core', 'hamstrings'],
  },
  {
    id: 'seed:overhead-squat',
    name: 'Overhead Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'shoulders'],
    secondaryMuscles: ['core', 'erectors', 'traps'],
  },
  {
    id: 'seed:front-rack-lunge',
    name: 'Front Rack Lunge',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'shoulders'],
  },
  {
    id: 'seed:zercher-squat',
    name: 'Zercher Squat',
    equipment: 'barbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'biceps', 'erectors', 'traps'],
  },
  {
    id: 'seed:sots-press',
    name: 'Sots Press',
    equipment: 'barbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['quads', 'glutes', 'core', 'triceps'],
  },

  // Dumbbell — functional / CrossFit
  {
    id: 'seed:db-snatch',
    name: 'Dumbbell Snatch',
    equipment: 'dumbbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders'],
    secondaryMuscles: ['traps', 'core', 'forearms'],
  },
  {
    id: 'seed:db-clean',
    name: 'Dumbbell Clean',
    equipment: 'dumbbell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'traps'],
    secondaryMuscles: ['shoulders', 'core', 'forearms'],
  },
  {
    id: 'seed:db-thruster',
    name: 'Dumbbell Thruster',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['quads', 'glutes', 'shoulders'],
    secondaryMuscles: ['triceps', 'core'],
  },
  {
    id: 'seed:db-push-press',
    name: 'Dumbbell Push Press',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'quads'],
    secondaryMuscles: ['triceps', 'glutes', 'core'],
  },
  {
    id: 'seed:devil-press',
    name: 'Devil Press',
    equipment: 'dumbbell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'glutes', 'hamstrings'],
    secondaryMuscles: ['chest', 'triceps', 'core', 'quads'],
  },
  {
    id: 'seed:db-front-squat',
    name: 'Dumbbell Front Squat',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'shoulders'],
  },
  {
    id: 'seed:renegade-row',
    name: 'Renegade Row',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats', 'core'],
    secondaryMuscles: ['biceps', 'shoulders', 'obliques'],
  },
  {
    id: 'seed:db-floor-press',
    name: 'Dumbbell Floor Press',
    equipment: 'dumbbell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
  },
  {
    id: 'seed:db-rdl',
    name: 'Dumbbell Romanian Deadlift',
    equipment: 'dumbbell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['erectors', 'forearms'],
  },

  // Kettlebell
  {
    id: 'seed:kb-snatch',
    name: 'Kettlebell Snatch',
    equipment: 'kettlebell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders'],
    secondaryMuscles: ['traps', 'core', 'forearms'],
  },
  {
    id: 'seed:kb-clean',
    name: 'Kettlebell Clean',
    equipment: 'kettlebell',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'traps'],
    secondaryMuscles: ['shoulders', 'core', 'forearms'],
  },
  {
    id: 'seed:kb-press',
    name: 'Kettlebell Press',
    equipment: 'kettlebell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
  },
  {
    id: 'seed:kb-push-press',
    name: 'Kettlebell Push Press',
    equipment: 'kettlebell',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'quads'],
    secondaryMuscles: ['triceps', 'glutes', 'core'],
  },
  {
    id: 'seed:double-kb-front-squat',
    name: 'Double Kettlebell Front Squat',
    equipment: 'kettlebell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'shoulders', 'erectors'],
  },
  {
    id: 'seed:kb-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    equipment: 'kettlebell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core'],
  },
  {
    id: 'seed:kb-floor-press',
    name: 'Kettlebell Floor Press',
    equipment: 'kettlebell',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
  },
  {
    id: 'seed:kb-row',
    name: 'Single-Arm Kettlebell Row',
    equipment: 'kettlebell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'core'],
  },
  {
    id: 'seed:turkish-getup',
    name: 'Turkish Get-up',
    equipment: 'kettlebell',
    pattern: 'core',
    primaryMuscles: ['core', 'shoulders'],
    secondaryMuscles: ['glutes', 'quads', 'obliques', 'triceps'],
  },
  {
    id: 'seed:kb-windmill',
    name: 'Kettlebell Windmill',
    equipment: 'kettlebell',
    pattern: 'core',
    primaryMuscles: ['obliques', 'shoulders'],
    secondaryMuscles: ['core', 'glutes', 'hamstrings'],
  },
  {
    id: 'seed:kb-halo',
    name: 'Kettlebell Halo',
    equipment: 'kettlebell',
    pattern: 'core',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['traps', 'obliques'],
  },
  {
    id: 'seed:kb-lunge',
    name: 'Kettlebell Lunge',
    equipment: 'kettlebell',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:kb-deadlift',
    name: 'Kettlebell Deadlift',
    equipment: 'kettlebell',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes', 'erectors'],
    secondaryMuscles: ['back', 'forearms'],
  },

  // Sandbag
  {
    id: 'seed:sandbag-clean',
    name: 'Sandbag Clean',
    equipment: 'sandbag',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'back'],
    secondaryMuscles: ['traps', 'core', 'forearms', 'shoulders'],
  },
  {
    id: 'seed:sandbag-bear-hug-squat',
    name: 'Sandbag Bear-Hug Squat',
    equipment: 'sandbag',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'erectors', 'forearms'],
  },
  {
    id: 'seed:sandbag-shoulder',
    name: 'Sandbag Shoulder',
    equipment: 'sandbag',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'back', 'shoulders'],
    secondaryMuscles: ['core', 'traps', 'forearms'],
  },
  {
    id: 'seed:sandbag-over-shoulder',
    name: 'Sandbag Over-Shoulder Toss',
    equipment: 'sandbag',
    pattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings', 'back'],
    secondaryMuscles: ['shoulders', 'core', 'erectors', 'traps'],
  },
  {
    id: 'seed:sandbag-press',
    name: 'Sandbag Press',
    equipment: 'sandbag',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core', 'chest'],
  },
  {
    id: 'seed:sandbag-getup',
    name: 'Sandbag Get-up',
    equipment: 'sandbag',
    pattern: 'core',
    primaryMuscles: ['core', 'glutes'],
    secondaryMuscles: ['shoulders', 'quads', 'obliques'],
  },
  {
    id: 'seed:sandbag-zercher-squat',
    name: 'Sandbag Zercher Squat',
    equipment: 'sandbag',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['core', 'biceps', 'erectors'],
  },
  {
    id: 'seed:sandbag-bear-hug-carry',
    name: 'Sandbag Bear-Hug Carry',
    equipment: 'sandbag',
    pattern: 'carry',
    primaryMuscles: ['core', 'forearms'],
    secondaryMuscles: ['shoulders', 'traps', 'quads'],
  },

  // Bodyweight / gymnastics — staples in functional gyms
  {
    id: 'seed:burpee',
    name: 'Burpee',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'quads', 'shoulders'],
    secondaryMuscles: ['triceps', 'core', 'glutes', 'hamstrings'],
  },
  {
    id: 'seed:box-jump',
    name: 'Box Jump',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:pistol-squat',
    name: 'Pistol Squat',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'calves'],
  },
  {
    id: 'seed:handstand-pushup',
    name: 'Handstand Push-up',
    equipment: 'bodyweight',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'triceps'],
    secondaryMuscles: ['core', 'traps'],
  },
  {
    id: 'seed:handstand-hold',
    name: 'Handstand Hold',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['triceps', 'forearms', 'traps'],
  },
  {
    id: 'seed:toes-to-bar',
    name: 'Toes-to-Bar',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lats', 'forearms', 'obliques'],
  },
  {
    id: 'seed:knees-to-elbows',
    name: 'Knees-to-Elbows',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['lats', 'forearms', 'obliques'],
  },
  {
    id: 'seed:bar-muscle-up',
    name: 'Bar Muscle-up',
    equipment: 'bodyweight',
    pattern: 'pull-vertical',
    primaryMuscles: ['lats', 'back', 'chest', 'triceps'],
    secondaryMuscles: ['biceps', 'shoulders', 'core', 'forearms'],
  },
  {
    id: 'seed:ring-muscle-up',
    name: 'Ring Muscle-up',
    equipment: 'bodyweight',
    pattern: 'pull-vertical',
    primaryMuscles: ['lats', 'back', 'chest', 'triceps'],
    secondaryMuscles: ['biceps', 'shoulders', 'core', 'forearms'],
  },
  {
    id: 'seed:ring-dip',
    name: 'Ring Dip',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    secondaryMuscles: ['core'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:ring-row',
    name: 'Ring Row',
    equipment: 'bodyweight',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'core', 'forearms'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:wall-walk',
    name: 'Wall Walk',
    equipment: 'bodyweight',
    pattern: 'push-vertical',
    primaryMuscles: ['shoulders', 'core'],
    secondaryMuscles: ['triceps', 'chest', 'forearms'],
  },
  {
    id: 'seed:air-squat',
    name: 'Air Squat',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:jumping-lunge',
    name: 'Jumping Lunge',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:broad-jump',
    name: 'Broad Jump',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'calves'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:l-sit',
    name: 'L-sit',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: ['quads', 'shoulders', 'forearms'],
  },
  {
    id: 'seed:double-under',
    name: 'Double Under',
    equipment: 'other',
    pattern: 'carry',
    primaryMuscles: ['calves'],
    secondaryMuscles: ['shoulders', 'forearms', 'core'],
  },

  // ---- Targeted accessories (added 2026-05) -----------------------------
  {
    id: 'seed:deficit-pushup',
    name: 'Deficit Push-up',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders', 'core'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:single-arm-db-row',
    name: 'Single-Arm DB Row',
    equipment: 'dumbbell',
    pattern: 'pull-horizontal',
    primaryMuscles: ['back', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'core', 'obliques'],
  },
  {
    id: 'seed:landmine-rotation',
    name: 'Landmine Rotation',
    equipment: 'barbell',
    pattern: 'core',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: ['shoulders', 'back', 'glutes'],
  },
  {
    id: 'seed:copenhagen-plank',
    name: 'Copenhagen Plank',
    equipment: 'bodyweight',
    pattern: 'core',
    primaryMuscles: ['obliques', 'core'],
    secondaryMuscles: ['glutes', 'hamstrings', 'shoulders'],
  },
  {
    id: 'seed:nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    equipment: 'bodyweight',
    pattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'calves', 'core'],
  },
  {
    id: 'seed:lateral-band-walk',
    name: 'Lateral Band Walk',
    equipment: 'other',
    pattern: 'squat',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['quads', 'hamstrings'],
  },
  {
    id: 'seed:ring-pushup',
    name: 'Ring Push-up',
    equipment: 'bodyweight',
    pattern: 'push-horizontal',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    isCompound: true,
    externallyLoadable: true,
  },
  {
    id: 'seed:clamshell',
    name: 'Clamshell',
    equipment: 'band',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['obliques'],
  },
  {
    id: 'seed:hip-abduction',
    name: 'Hip Abduction',
    equipment: 'machine',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    equipment: 'bodyweight',
    pattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
  },
  {
    id: 'seed:backward-sled-drag',
    name: 'Backward Sled Drag',
    equipment: 'other',
    pattern: 'carry',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'calves', 'core'],
  },
  {
    id: 'seed:single-leg-calf-raise',
    name: 'Standing Single-Leg Calf Raise',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:seated-db-calf-raise',
    name: 'Seated DB Calf Raise',
    equipment: 'dumbbell',
    pattern: 'squat',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
  },
  {
    id: 'seed:tibialis-raise',
    name: 'Tibialis Raise',
    equipment: 'bodyweight',
    pattern: 'squat',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
  },
];
